//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestActiveCode
    {
        public int RestActiveCodeId { get; set; }
        public int UserId { get; set; }
        public string RestCode { get; set; }
        public string RestName { get; set; }
        public string TokenId { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> DeletedFlg { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    }
}
