//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.Framework.Views.Security
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    #line 1 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
    using BCS.Framework.WebExtensions.Label;
    
    #line default
    #line hidden
    
    #line 4 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Security/Forgot.cshtml")]
    public class _Page_Views_Security_Forgot_cshtml : System.Web.Mvc.WebViewPage<BCS.Framework.Models.ForgotModel>
    {
#line hidden

        public _Page_Views_Security_Forgot_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {






            
            #line 6 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
  
    ViewBag.Title = "Forgot Password - Smart Systems Pro";
    Layout = "~/Views/Shared/LayoutPage.cshtml";


            
            #line default
            #line hidden
WriteLiteral(@"
<div class=""col-xs-12"">
    <div class=""form-group"">
        <br /><br /><br /><br /><br />
        <div class=""text-center"" style=""font-size: 22pt; font-weight: normal; color: #FFF"">FORGOT PASSWORD</div>
        <br /><br />
    </div>
</div>
<div class=""clearfix""></div>
<div class="""" style=""height:420px; width:850px; margin: 0 auto;background: #FFF;-moz-border-radius: 2em"">
    <div class=""row"" style=""padding: 10px;-moz-border-radius: 1em"">
        <div class=""col-xs-7"">
");


            
            #line 22 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
             using (Html.BeginForm("Forgot", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "logon-form form-horizontal", id = "frm-fogot" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"error\">\r\n                    ");


            
            #line 25 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
               Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");


            
            #line 26 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");



WriteLiteral(@"                <div class=""form-group"">
                    <div class=""col-xs-12"">
                        <p>If you need help resetting you password, we can help by sending you a link to rest it.</p>
                        <li>Enter either the email address and captcha on the account.</li>
                        <li>Click Send.</li>
                        <li>Check your inbox for a password reset email.</li>
                        <li>Click on the URL provided in the email and enter a new password .</li>
                        <br />
                    </div>
                </div>
");



WriteLiteral("                <div class=\"form-group\">\r\n                    ");


            
            #line 39 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
               Write(Html.LabelForRequire(model => model.Email, new { @class = "col-xs-2 txt-right", style = "margin-top:10px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"col-xs-10\">\r\n                        ");


            
            #line 41 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
                   Write(Html.TextBoxFor(model => model.Email, new { placeholder = "Email", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span class=\"error\">");


            
            #line 42 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <div class=\"form-group\">\r\n                    ");


            
            #line 46 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
               Write(Html.LabelForRequire(model => model.Sum, new { @class = "col-xs-2 txt-right", style = "margin-top: 10px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"col-xs-10\">\r\n                        <div class" +
"=\"col-xs-6\" style=\"margin-left: -15px\">\r\n                            ");


            
            #line 49 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
                       Write(Html.TextBoxFor(model => model.Sum, new { placeholder = "Sum", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div class=\"col-xs-6\">\r" +
"\n                            <img alt=\"Captcha\" src=\"");


            
            #line 52 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
                                               Write(Url.Action("CaptchaImage"));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"\" />\r\n                        </div>\r\n                        <div style" +
"=\"clear: both\"></div>\r\n                        <span class=\"error\">");


            
            #line 55 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.Sum));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <br />\r\n");



WriteLiteral(@"                <div class=""form-group logon-toolbar"">
                    <div class=""col-xs-12"" align=""center""><input type=""submit"" class=""btn btn-primary button btnOk"" id=""btnForgot"" value="" Send "" style=""width:150px"" /></div>
                </div>
");


            
            #line 62 "D:\Work\BCS\BCS.Framework\Views\Security\Forgot.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>
        <div class=""col-xs-5"" style=""border-left: 1px solid darkolivegreen"">
            <div class=""form-group"">
                <b>Already have Smart System Pro account ?</b>
            </div>
            <div class=""form-group"">
                <span>Click Sign Up button to access Budget Creator</span>
            </div>
            <br /><br />
            <div class=""form-group text-center"">
                <input type=""button"" class=""btn btn-primary button btnOk"" id=""btnSignUp"" value=""Sign Up"" style=""width:150px"" />
            </div>
            <br /><br />
            <div class=""form-group"">
                <span><b>Having trouble?</b> Feel free to contact us</span>
            </div>
            <br />
            <div class=""form-group text-center"">
                <input type=""submit"" class=""btn btn-primary button btnOk"" id=""btnContactUs"" value=""Contact us"" style=""width:150px"" />
            </div>
            <div class=""form-group""></div>
            <div class=""form-group""></div>
        </div>
    </div>
</div>

<script type=""text/javascript"">
    $(document).ready(function () {
        $(""#btnForgot"").click(function () {
            var form = $(""#frm-fogot"");
            form.validate();
            var isValid = form.valid();
            if (isValid) {
                return showProcessing();
            }
        });
    });
</script>


");


        }
    }
}
