#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Views\Security\Login.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Security\Login.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Security\Login.cshtml"
    using BCS.Framework.WebExtensions.Label;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Security/Login.cshtml")]
    public partial class _Views_Security_Login_cshtml : System.Web.Mvc.WebViewPage<BCS.Framework.Models.LoginModel>
    {
        public _Views_Security_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Security\Login.cshtml"
  
    ViewBag.Title = "Sign In - Budget Creator";
    Layout = "~/Views/Shared/LayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <br /><br /><br /><br /><br />\r\n        <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"font-size: 22pt; font-weight: normal; color: #FFF\"");

WriteLiteral(">SIGN IN </div>\r\n        <br /><br />\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"height:420px; width:850px; margin: 0 auto;background: #FFF;-moz-border-ra" +
"dius: 2em\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding: 10px;-moz-border-radius: 1em\"");

WriteLiteral(">\r\n        <br />\r\n        <div");

WriteLiteral(" class=\"col-xs-7\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Security\Login.cshtml"
           Write(Html.Label("lblInfo", "If you are a registered user, please enter your email and password.", new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 26 "..\..\Views\Security\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Security\Login.cshtml"
             using (Html.BeginForm("Login", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "logon-form form-horizontal", id = "frm-login" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"error\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Security\Login.cshtml"
               Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Views\Security\Login.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\Security\Login.cshtml"
               Write(Html.LabelForRequire(model => model.UserName, new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 37 "..\..\Views\Security\Login.cshtml"
                   Write(Html.TextBoxFor(model => model.UserName, new { placeholder = "User Name", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span");

WriteLiteral(" class=\"error\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Security\Login.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Views\Security\Login.cshtml"
               Write(Html.LabelForRequire(model => model.Password, new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 44 "..\..\Views\Security\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Views\Security\Login.cshtml"
                   Write(Html.PasswordFor(model => model.Password, new { placeholder = "Password", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span");

WriteLiteral(" class=\"error\"");

WriteLiteral(">");

            
            #line 48 "..\..\Views\Security\Login.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.Password));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"padding-top:6px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 53 "..\..\Views\Security\Login.cshtml"
                   Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 54 "..\..\Views\Security\Login.cshtml"
                   Write(Html.LabelFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <br />\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary button btnOk\"");

WriteLiteral(" id=\"btnSignIn\"");

WriteLiteral(" value=\"Sign In\"");

WriteLiteral(" style=\"width:150px\"");

WriteLiteral(" />\r\n                </div>\r\n");

WriteLiteral("                <br />\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Views\Security\Login.cshtml"
               Write(Html.ActionLink("Forgot password?", "Forgot", "Security", new { returnUrl = ViewBag.ReturnUrl ?? string.Empty }, new { @class = "button btnForgot" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <br />\r\n");

            
            #line 66 "..\..\Views\Security\Login.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(" style=\"border-left: 1px solid darkolivegreen\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <b>Already have Smart System Pro account ?</b>\r\n            </" +
"div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <span>Click Sign Up button to access Budget Creator</span>\r\n  " +
"          </div>\r\n            <br /><br />\r\n            <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary button btnOk\"");

WriteLiteral(" id=\"btnSignUp\"");

WriteLiteral(" value=\"Sign Up\"");

WriteLiteral(" style=\"width:150px\"");

WriteLiteral(" />\r\n            </div>\r\n            <br /><br />\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <span><b>Having trouble?</b> Feel free to contact us</span>\r\n " +
"           </div>\r\n            <br />\r\n            <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary button btnOk\"");

WriteLiteral(" id=\"btnContactUs\"");

WriteLiteral(" value=\"Contact us\"");

WriteLiteral(" style=\"width:150px\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(document).ready(function () {
        $(""#btnSignIn"").click(function () {
            var form = $(""#frm-login"");
            form.validate();
            var isValid = form.valid();
            if (isValid) {
                return showProcessing();
            }
        });
    });
</script>

");

        }
    }
}
#pragma warning restore 1591
