//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.Framework.Views.Security
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    #line 1 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 2 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 3 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
    using BCS.Framework.WebExtensions.Label;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Security/Login.cshtml")]
    public class _Page_Views_Security_Login_cshtml : System.Web.Mvc.WebViewPage<BCS.Framework.Models.LoginModel>
    {
#line hidden

        public _Page_Views_Security_Login_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {





            
            #line 5 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
  
    ViewBag.Title = "Sign In - Budget Creator";
    Layout = "~/Views/Shared/LayoutPage.cshtml";


            
            #line default
            #line hidden
WriteLiteral(@"

<div class=""col-xs-12"">
    <div class=""form-group"">
        <br /><br /><br /><br /><br />
        <div class=""text-center"" style=""font-size: 22pt; font-weight: normal; color: #FFF"">SIGN IN </div>
        <br /><br />
    </div>
</div>
<div class=""clearfix""></div>
<div class="""" style=""height:420px; width:850px; margin: 0 auto;background: #FFF;-moz-border-radius: 2em"">
    <div class=""row"" style=""padding: 10px;-moz-border-radius: 1em"">
        <br />
        <div class=""col-xs-7"">
            <div class=""form-group"">
                ");


            
            #line 24 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
           Write(Html.Label("lblInfo", "If you are a registered user, please enter your email and password.", new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 26 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
             using (Html.BeginForm("Login", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "logon-form form-horizontal", id = "frm-login" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"error\">\r\n                    ");


            
            #line 29 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
               Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");


            
            #line 30 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");



WriteLiteral("                <div class=\"form-group\">\r\n                    ");


            
            #line 33 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
               Write(Html.LabelForRequire(model => model.UserName, new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");



WriteLiteral("                <div class=\"form-group\">\r\n                    <div class=\"col-xs-" +
"12\">\r\n                        ");


            
            #line 37 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
                   Write(Html.TextBoxFor(model => model.UserName, new { placeholder = "User Name", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span class=\"error\">");


            
            #line 38 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <div class=\"form-group\">\r\n                    ");


            
            #line 42 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
               Write(Html.LabelForRequire(model => model.Password, new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");


            
            #line 44 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"form-group\">\r\n                    <div class=\"col-xs-" +
"12\">\r\n                        ");


            
            #line 47 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
                   Write(Html.PasswordFor(model => model.Password, new { placeholder = "Password", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <span class=\"error\">");


            
            #line 48 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
                                       Write(Html.ValidationMessageFor(model => model.Password));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <div class=\"form-group\" style=\"\">\r\n                    <div class" +
"=\"col-xs-12\">\r\n                        ");


            
            #line 53 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
                   Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 54 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
                   Write(Html.LabelFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");



WriteLiteral("                <br />\r\n");



WriteLiteral("                <div class=\"form-group text-center\">\r\n                    <input " +
"type=\"submit\" class=\"btn btn-primary button btnOk\" id=\"btnSignIn\" value=\"Sign In" +
"\" style=\"width:150px\" />\r\n                </div>\r\n");



WriteLiteral("                <br />\r\n");



WriteLiteral("                <div class=\"form-group text-center\">\r\n                    ");


            
            #line 63 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
               Write(Html.ActionLink("Forgot password?", "Forgot", "Security", new { returnUrl = ViewBag.ReturnUrl ?? string.Empty }, new { @class = "button btnForgot" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");



WriteLiteral("                <br />\r\n");


            
            #line 66 "D:\Work\BCS\BCS.Framework\Views\Security\Login.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>
        <div class=""col-xs-5"" style=""border-left: 1px solid darkolivegreen"">
            <div class=""form-group"">
                <b>Already have Smart System Pro account ?</b>
            </div>
            <div class=""form-group"">
                <span>Click Sign Up button to access Budget Creator</span>
            </div>
            <br /><br />
            <div class=""form-group text-center"">
                <input type=""button"" class=""btn btn-primary button btnOk"" id=""btnSignUp"" value=""Sign Up"" style=""width:150px"" />
            </div>
            <br /><br />
            <div class=""form-group"">
                <span><b>Having trouble?</b> Feel free to contact us</span>
            </div>
            <br />
            <div class=""form-group text-center"">
                <input type=""button"" class=""btn btn-primary button btnOk"" id=""btnContactUs"" value=""Contact us"" style=""width:150px"" />
            </div>
            <div class=""form-group""></div>
            <div class=""form-group""></div>
        </div>
    </div>
</div>


<script type=""text/javascript"">
    $(document).ready(function () {
        $(""#btnSignIn"").click(function () {
            var form = $(""#frm-login"");
            form.validate();
            var isValid = form.valid();
            if (isValid) {
                return showProcessing();
            }
        });
    });
</script>

");


        }
    }
}
