#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\Views\Security\ResetPassword.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Security\ResetPassword.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Security\ResetPassword.cshtml"
    using BCS.Framework.WebExtensions.Label;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Security/ResetPassword.cshtml")]
    public partial class _Views_Security_ResetPassword_cshtml : System.Web.Mvc.WebViewPage<BCS.Framework.Models.ChangePasswordModel>
    {
        public _Views_Security_ResetPassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Security\ResetPassword.cshtml"
  
    ViewBag.Title = "Change Password - Budget Creator";
    Layout = "~/Views/Shared/LayoutPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <br /><br /><br /><br /><br />\r\n        <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"font-size: 22pt; font-weight: normal; color: #FFF\"");

WriteLiteral(">CHANGE YOUR PASSWORD</div>\r\n        <br /><br />\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 18 "..\..\Views\Security\ResetPassword.cshtml"
 using (Html.BeginForm("ResetPassword", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "logon-form form-horizontal", id = "frm-login" }))
{
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Security\ResetPassword.cshtml"
     if (ViewBag.Time_mail != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"height:420px; width:850px; margin: 0 auto;background: #FFF;-moz-border-ra" +
"dius: 2em\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding: 30px;-moz-border-radius: 1em\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-7\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"error\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Views\Security\ResetPassword.cshtml"
                   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\Security\ResetPassword.cshtml"
                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Security\ResetPassword.cshtml"
               Write(Html.HiddenFor(m => m.ForgotCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <p><b>Change your Budget Creator Account password." +
"</b></p>\r\n                            <span");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">\r\n                                Notes: This link will be expired after ");

            
            #line 34 "..\..\Views\Security\ResetPassword.cshtml"
                                                                  Write(ViewBag.Time_mail.Hours);

            
            #line default
            #line hidden
WriteLiteral(" hour(s) ");

            
            #line 34 "..\..\Views\Security\ResetPassword.cshtml"
                                                                                                   Write(ViewBag.Time_mail.Minutes);

            
            #line default
            #line hidden
WriteLiteral(" minute(s).\r\n                            </span>\r\n                        </div>\r" +
"\n                    </div>\r\n               \r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\Views\Security\ResetPassword.cshtml"
                   Write(Html.Label("NewPassword", "New Password", new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 42 "..\..\Views\Security\ResetPassword.cshtml"
                       Write(Html.PasswordFor(model => model.PassWord, new { placeholder = "New Password", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <span");

WriteLiteral(" class=\"error\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Security\ResetPassword.cshtml"
                                           Write(Html.ValidationMessageFor(model => model.PassWord));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </div>\r\n                    </div>\r\n            " +
"        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Views\Security\ResetPassword.cshtml"
                   Write(Html.Label("ConfirmPassword", "Confirm Password", new { @class = " col-xs-12 txt-right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 49 "..\..\Views\Security\ResetPassword.cshtml"
                       Write(Html.PasswordFor(model => model.ConfirmPassword, new { placeholder = "Confirm Password", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <span");

WriteLiteral(" class=\"error\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\Security\ResetPassword.cshtml"
                                           Write(Html.ValidationMessageFor(model => model.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </div>\r\n                    </div>\r\n            " +
"        <br />\r\n                    <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary button btnOk\"");

WriteLiteral(" id=\"btnForgot\"");

WriteLiteral(" value=\"Change\"");

WriteLiteral(" style=\"width:150px\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <br />\r\n                    " +
"<div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 59 "..\..\Views\Security\ResetPassword.cshtml"
                   Write(Html.ActionLink("Back To Sign In", "Login", "Security", new { @class = "button btnForgot" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <br />\r\n\r\n                </div" +
">\r\n                <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(" style=\"padding-left: 30px !important; border-left: 1px solid darkolivegreen\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <b>Already have Smart System Pro account ?</b>\r\n      " +
"              </div>\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <span>Click Sign Up button to access Budget Creator</s" +
"pan>\r\n                    </div>\r\n                    <br /><br />\r\n            " +
"        <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary button btnOk\"");

WriteLiteral(" id=\"btnSignUp\"");

WriteLiteral(" value=\"Sign Up\"");

WriteLiteral(" style=\"width:150px\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <br /><br />\r\n              " +
"      <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <span><b>Having trouble?</b> Feel free to contact us</" +
"span>\r\n                    </div>\r\n                    <br />\r\n                 " +
"   <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary button btnOk\"");

WriteLiteral(" id=\"btnContactUs\"");

WriteLiteral(" value=\"Contact us\"");

WriteLiteral(" style=\"width:150px\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 88 "..\..\Views\Security\ResetPassword.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"height:220px; width:550px; margin: 0 auto;background: #FFF;-moz-border-ra" +
"dius: 2em\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-12 text-center\"");

WriteLiteral(" style=\"padding-top:30px; padding-bottom:50px;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"color: red; font-size:12pt;\"");

WriteLiteral(">\r\n                    The link to reset your password is expired.\r\n             " +
"   </span>\r\n                <br />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 99 "..\..\Views\Security\ResetPassword.cshtml"
           Write(Html.ActionLink("Back To Sign In", "Login", "Security", new { @class = "button btnForgot" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 102 "..\..\Views\Security\ResetPassword.cshtml"
    }
            
            #line default
            #line hidden
            
            #line 102 "..\..\Views\Security\ResetPassword.cshtml"
     
}

            
            #line default
            #line hidden
WriteLiteral("<script>\r\n    $(document).ready(function () {\r\n        setTimeout(function () {\r\n" +
"            $(\"#PassWord\").val(\'\');\r\n        }, 100);\r\n    });\r\n</script>     ");

        }
    }
}
#pragma warning restore 1591
