//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.Framework.Views.Security
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    #line 1 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
    using System.Activities.Expressions;
    
    #line default
    #line hidden
    
    #line 2 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 4 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
    using Kendo.Mvc.UI;
    
    #line default
    #line hidden
    
    #line 5 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
    using Recaptcha.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Security/ResetResult.cshtml")]
    public class _Page_Views_Security_ResetResult_cshtml : System.Web.Mvc.WebViewPage<BCS.Framework.Models.ForgotModel>
    {
#line hidden

        public _Page_Views_Security_ResetResult_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {







            
            #line 7 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
  
    ViewBag.Title = "Change Password Result- Budget Creator";
    Layout = "~/Views/Shared/LayoutPage.cshtml";


            
            #line default
            #line hidden
WriteLiteral(@"

<div class=""col-xs-12"">
    <div class=""form-group"">
        <br /><br /><br /><br /><br />
        <div class=""text-center"" style=""font-size: 22pt; font-weight: normal; color: #FFF"">CHANGE YOUR PASSWORD</div>
        <br /><br />
    </div>
</div>
<div class=""clearfix""></div>
<div class="""" style=""height:420px; width:850px; margin: 0 auto;background: #FFF;-moz-border-radius: 2em"">
    <div class=""row"" style=""padding: 10px;-moz-border-radius: 1em"">
        <div class=""col-xs-7"">
");


            
            #line 24 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
             using (Html.BeginForm("Forgot", "Security", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "logon-form form-horizontal", id = "frm-fogot" }))
            {
                
            
            #line default
            #line hidden
            
            #line 26 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
           Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 26 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
                                             
                
            
            #line default
            #line hidden
            
            #line 27 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 27 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral(@"                <div class=""form-group"">
                    <div class=""col-xs-12"" style=""color: blue"">
                        <p>Password has been reset successfully.</p>
                        <br />
                    </div>
                </div>
");



WriteLiteral("                <br />\r\n");



WriteLiteral("                <div class=\"form-group logon-toolbar\">\r\n                    <div " +
"class=\"col-xs-12\" align=\"center\">");


            
            #line 36 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
                                                     Write(Html.ActionLink("Back To Sign In", "Login", "Security", new { @class = "btn btn-primary button btnOk", @style = "width:150px", @onclick = "return showProcessing();" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n");


            
            #line 38 "D:\Work\BCS\BCS.Framework\Views\Security\ResetResult.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>
        <div class=""col-xs-5"" style=""border-left: 1px solid darkolivegreen"">
            <div class=""form-group"">
                <b>Already have Smart System Pro account ?</b>
            </div>
            <div class=""form-group"">
                <span>Click Sign Up button to access Budget Creator</span>
            </div>
            <br /><br />
            <div class=""form-group text-center"">
                <input type=""button"" class=""btn btn-primary button btnOk"" id=""btnSignUp"" value=""Sign Up"" style=""width:150px"" />
            </div>
            <br /><br />
            <div class=""form-group"">
                <span><b>Having trouble?</b> Feel free to contact us</span>
            </div>
            <br />
            <div class=""form-group text-center"">
                <input type=""submit"" class=""btn btn-primary button btnOk"" id=""btnContactUs"" value=""Contact us"" style=""width:150px"" />
            </div>
            <div class=""form-group""></div>
            <div class=""form-group""></div>
        </div>
    </div>
</div>




");


        }
    }
}
