//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCS.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCS.Web.App_LocalResources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Date.
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/Add New Record.
        /// </summary>
        public static string BtnAddOrEdit {
            get {
                return ResourceManager.GetString("BtnAddOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string BtnExportExcel {
            get {
                return ResourceManager.GetString("BtnExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string BtnSummary {
            get {
                return ResourceManager.GetString("BtnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMEX.
        /// </summary>
        public static string EndDayReport_Amex {
            get {
                return ResourceManager.GetString("EndDayReport_Amex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverage.
        /// </summary>
        public static string EndDayReport_Beverage {
            get {
                return ResourceManager.GetString("EndDayReport_Beverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle Beer.
        /// </summary>
        public static string EndDayReport_BottleBeer {
            get {
                return ResourceManager.GetString("EndDayReport_BottleBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catering Deposit.
        /// </summary>
        public static string EndDayReport_CateringDeposit {
            get {
                return ResourceManager.GetString("EndDayReport_CateringDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string EndDayReport_Date {
            get {
                return ResourceManager.GetString("EndDayReport_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string EndDayReport_Day {
            get {
                return ResourceManager.GetString("EndDayReport_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string EndDayReport_Discover {
            get {
                return ResourceManager.GetString("EndDayReport_Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Beer.
        /// </summary>
        public static string EndDayReport_DraftBeer {
            get {
                return ResourceManager.GetString("EndDayReport_DraftBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string EndDayReport_Food {
            get {
                return ResourceManager.GetString("EndDayReport_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card Sold.
        /// </summary>
        public static string EndDayReport_GiftCardSold {
            get {
                return ResourceManager.GetString("EndDayReport_GiftCardSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Certificate.
        /// </summary>
        public static string EndDayReport_GiftCertificate {
            get {
                return ResourceManager.GetString("EndDayReport_GiftCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Sale.
        /// </summary>
        public static string EndDayReport_GrossSales {
            get {
                return ResourceManager.GetString("EndDayReport_GrossSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Charges.
        /// </summary>
        public static string EndDayReport_HouseCharges {
            get {
                return ResourceManager.GetString("EndDayReport_HouseCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquor.
        /// </summary>
        public static string EndDayReport_Liquor {
            get {
                return ResourceManager.GetString("EndDayReport_Liquor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Card.
        /// </summary>
        public static string EndDayReport_MasterCard {
            get {
                return ResourceManager.GetString("EndDayReport_MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Sales.
        /// </summary>
        public static string EndDayReport_NetSales {
            get {
                return ResourceManager.GetString("EndDayReport_NetSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over / Short.
        /// </summary>
        public static string EndDayReport_OverShort {
            get {
                return ResourceManager.GetString("EndDayReport_OverShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Out.
        /// </summary>
        public static string EndDayReport_PaidOut {
            get {
                return ResourceManager.GetString("EndDayReport_PaidOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof.
        /// </summary>
        public static string EndDayReport_Proof {
            get {
                return ResourceManager.GetString("EndDayReport_Proof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        public static string EndDayReport_SalesTax {
            get {
                return ResourceManager.GetString("EndDayReport_SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips Collected.
        /// </summary>
        public static string EndDayReport_TipsCollectd {
            get {
                return ResourceManager.GetString("EndDayReport_TipsCollectd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Day Reporting.
        /// </summary>
        public static string EndDayReport_Title {
            get {
                return ResourceManager.GetString("EndDayReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cash.
        /// </summary>
        public static string EndDayReport_TotalCash {
            get {
                return ResourceManager.GetString("EndDayReport_TotalCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string EndDayReport_Visa {
            get {
                return ResourceManager.GetString("EndDayReport_Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine.
        /// </summary>
        public static string EndDayReport_Wine {
            get {
                return ResourceManager.GetString("EndDayReport_Wine", resourceCulture);
            }
        }
    }
}
